In [ ]:
from glob import glob
import platform
import os
if platform.system()=='Linux':
  from google.colab import drive
  drive.mount('/content/drive')
  os.chdir('/content/drive/My Drive/')
  sep='/'
else:
  sep='\\'
print(os.getcwd())

MessageError: Error: credential propagation was unsuccessful

In [ ]:
import sqlite3 as lite

In [ ]:
con = lite.connect('Team3/dbmsproj.sqlite')

In [ ]:
def transact(con, sql):
    try:
        con.execute(sql)
        con.commit()
    except Exception as e:
        con.rollback()
        print(e)

In [ ]:
import pandas as pd

**READING DATA FROM THE SPREADSHEET**

In [ ]:
# bb = pd.read_excel("Team3/transaction_data.xlsx",sheet_name='bankbalance')
# Userz = pd.read_excel("Team3/transaction_data.xlsx",sheet_name='Users')
# catgor = pd.read_excel("Team3/transaction_data.xlsx",sheet_name='Category')
# budgett = pd.read_excel("Team3/transaction_data.xlsx",sheet_name='Budget')

In [ ]:
pd.read_sql("SELECT * FROM transactions LIMIT 5",con)

,transaction_id,senders_id,receivers_id,amount,date,time,category_id
0,1,Atheendre_ram,ApolloHealth_12345,10,2024-05-04,18:45:13,MED
1,2,Atheendre_ram,ApolloHealth_12345,10,2024-05-04,18:45:47,MED
2,3,Atheendre_ram,ApolloHealth_12345,10,2024-05-04,18:46:28,MED
3,4,Ramyashree_04,ApolloHealth_12345,10,2024-05-04,18:47:10,MED
4,5,Ramyashree_04,ApolloHealth_12345,10,2024-05-04,18:47:42,MED

**CREATING TABLE Users**

In [ ]:
# con.execute("DROP TABLE IF EXISTS Users")
con.execute("""CREATE TABLE IF NOT EXISTS Users (
                username TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                email TEXT UNIQUE CHECK (email LIKE '_%@_%._%'),
                pin TEXT
            )""")
con.commit()

In [ ]:
# con.execute("Drop table if exists Category")
con.execute("""CREATE TABLE if not exists Category (
    category_id text primary key,
    category_name TEXT NOT NULL
);
""")
con.commit()

In [ ]:
# con.execute("Drop table if exists Budget")
con.execute("""CREATE TABLE if not exists Budget (
    budget_id INTEGER PRIMARY KEY autoincrement,
    username text,
    category_id text,
    budget_amount REAL,
    total_amount real,
    start_date text,
    end_date text,
    FOREIGN KEY (username) REFERENCES Users(username),
    FOREIGN KEY (category_id) REFERENCES Categories(category_id)
);

""")
con.commit()

In [ ]:
# con.execute("drop table if exists balance")
con.execute("""CREATE TABLE if not exists balance (
    bankbalance_id INTEGER PRIMARY KEY AUTOINCREMENT,
    username text,
    bankbalance int check (bankbalance>=0),
    FOREIGN KEY (username) REFERENCES Users(username)
);
""")
con.commit()

In [ ]:
import hashlib
def encrypt(pin):
  return hashlib.sha256(str(pin).encode()).hexdigest()
#hashlib.sha256 is creating a new hash object which takes a string as input and converts
#it into byte representation using encode() and then hashes using hexadecimal values.

In [ ]:
# for row in Userz.itertuples(index=False):
#     encrypted_pin = encrypt(row.pin)
#     con.execute("INSERT INTO Users (username, name, email, pin) VALUES (?, ?, ?, ?)",
#                    (row.username, row.name, row.email, encrypted_pin))

#Need not run everytime
#Iterating over the whole data considering each row as a tuple: Where pin is encrypted using encrypt() and stored in encrypt_pin
'''Then we are inserting all the values into the users table using placeholders.'''

'Then we are inserting all the values into the users table using placeholders.'

In [ ]:
con.commit()

In [ ]:
con.execute("select * from Users").fetchone()

('aarav_k01',
 'Aarav Kumar',
 'aaravk.bsc23@rvu.edu.in',
 'bcb15f821479b4d5772bd0ca866c00ad5f926e3580720659cc80d39c9d09802a')

# what is going on here
"""for row in userz.itertuples(index=False): This line starts a loop that iterates over each row in the userz DataFrame.
 itertuples() is a Pandas function that returns an iterator yielding namedtuples for each row in the DataFrame.
  Setting index=False ensures that the index of the DataFrame is not included in the tuples.
con.execute("INSERT INTO Users VALUES (?, ?, ?)", row): Within each iteration of the loop, this line executes an SQL INSERT statement
. It inserts a row into the "Users" table using the values from the current row of the DataFrame (row).
 The question marks (?) are placeholders for the values to be inserted.
 This is a parameterized query where values from the DataFrame row are substituted into the placeholders."""

In [ ]:
# for row in catgor.itertuples(index=False):
#     con.execute("INSERT INTO category VALUES (?,?)", row)
# con.commit()

#need not run every time
#Iterating through each row in excel and inserting the tuples as values into the category table

In [ ]:
con.execute("select * from category").fetchall()

[('CE', 'Casual Entertainment'),
 ('F&B', 'Food'),
 ('TRVL', 'Travel'),
 ('SHP', 'Shopping'),
 ('GRC', 'Groceries'),
 ('MED', 'Medicine'),
 ('EDU', 'Studies'),
 ('DOM', 'Domestic'),
 ('PRE', 'Prepaid'),
 ('ELEC', 'Electricity')]

In [ ]:
# for row in bb.itertuples(index=False):
#     con.execute("INSERT INTO balance(username,bankbalance) VALUES (?,?)", row)
# con.execute("select * from balance").fetchall()

In [ ]:
con.execute("select * from Budget").fetchone()
z= budgett.iloc[:,:4]
z
for row in z.itertuples(index=False):
    con.execute("INSERT INTO Budget(username,category_id,budget_amount,total_amount,start_date,end_date) VALUES (?,?,?,?,'1-04-2024','30-04-20204')", row)
con.execute("select * from Budget").fetchall()
con.commit()

#Slicing budget data from the excel.
#Iterating over the data and inserting the data as tuples into the budget table

NameError: name 'budgett' is not defined

In [ ]:
# con.execute("select * from Budget where username= 'Atheendre_ram'").fetchall()

In [ ]:
con.execute("delete   from Budget Where category_id ='MISC'")
con.execute("delete from category where category_id = 'MISC'")

In [ ]:
con.commit()

In [ ]:
con.execute("""CREATE TABLE IF NOT EXISTS transactions (
    transaction_id INTEGER PRIMARY KEY AUTOINCREMENT,
    senders_id TEXT NOT NULL,
    receivers_id TEXT NOT NULL,
    amount INTEGER CHECK(amount > 0),
    date TEXT DEFAULT (DATE(CURRENT_TIMESTAMP)),
    time TEXT,
    category_id TEXT,
    FOREIGN KEY (senders_id) REFERENCES Users(username) ON DELETE RESTRICT,
    FOREIGN KEY (receivers_id) REFERENCES Users(username) ON DELETE RESTRICT,
    FOREIGN KEY (category_id) REFERENCES Category(category_id)
);
""")

con.commit()


#Creating transactions table
#Transactions table is the child table of users and category tables.

In [ ]:
con.execute("""
CREATE TRIGGER if not exists insert_timestamp
AFTER INSERT ON transactions
BEGIN
    UPDATE transactions
    SET date = DATE('now', 'localtime'), time = TIME('now', '+05:30')
    WHERE rowid = NEW.rowid;
END;
""")
con.commit()
#Triggered after inserting data into transactions table.
#Updating the date in the transactions table to the time the transaction is done
#current timestamp provides time and date, having date(timestamp) returns only the current date, same for time
#fk connects a column in the given table to another tables pk, this means u can access cols of the other connected table
#on insert restrict allows us to restrict change/insertion/deletion in the child table that violates the foreign key constraint
#a trigger works during crud ops, here the triggers r raised if the username in transactions is not present in users username
#tried using on insert restrict and DEFERRABLE INITIALLY DEFERRED didnt work therefore chose a trigger
#raise(abort) raises an error saying invalid id, of type abort(which halts the current sql statement and rollsback to the previous state,
#SELECT 1 is to check for the existence of a row that meets certain conditions but you don't need to retrieve any actual data from the table. It's a way to check whether a condition is true without incurring the overhead of retrieving any specific columns.

In [ ]:
con.execute("""CREATE TRIGGER if not exists update_balance
AFTER INSERT ON transactions
BEGIN
    UPDATE balance
    SET bankbalance = bankbalance - NEW.amount
    WHERE username = NEW.senders_id;

    UPDATE balance
    SET bankbalance = bankbalance + NEW.amount
    WHERE username = NEW.receivers_id;
END;
""")
#Triggered after data is inserted into transactions table
#Updating the sender's bank balance by deducting the transaction amount and adding the same transaction amount is added to the reciever's bankbalance.

Use cases of our transaction system.
1. send and receive transactions, the amount is automatically deducted from the sender and increased in the receiver
2. to send and receive transactions, the amount is to be present in the balance of the sender and the pin entered must match the pin stored in the database(prototype)
3. the database also checks if the sender and receiver are both registered in the users table
4. you can get a users bankbalance and transaction history by entering the pin
5. ask for username and password while logging in

In [ ]:
receiver_categories = {
    'AmazedByDeals2023': 'SHP',
    'FlipkartFanatic101': 'SHP',
    'FoodieBangalore99': 'F&B',
    'UberUser_BLR123': 'TRVL',
    'MetroCard_1234567890': 'TRVL',
    'PolarBear_Environmental': 'F&B',
    'Zomatoholic20': 'F&B',
    'Jio_SIM_1234567890': 'PRE',
    'Netflix_Buff': 'CE',
    'TravelExplorer55': 'TRVL',
    'LPG_Consumer_12345': 'DOM',
    'MingosFan_BLR': 'F&B',
    'ApolloHealth_12345': 'MED',
    'Bigb_2342':'GRC',
    'Sapna_house10':'EDU',
    'Bscom_12': 'ELEC',
    'Bhel_189': 'ELEC'
}

#Receiver who belongs to an organization, they are assigned respective
#There are 10categories and the above are the users in that categories.

In [ ]:
cursor = con.cursor()

# Define a function to check if budget exceeded
def check_budget(sender_id, category_id, amount):
    # Fetch budget amount for the sender and category
    cursor.execute("SELECT budget_amount FROM Budget WHERE username = ? AND category_id = ?", (sender_id, category_id))
    budget_amount = cursor.fetchone()
    if budget_amount and amount > budget_amount[0]:
        print(budget_amount)
        print(amount)
        return True  # Budget exceeded
    else:
        return False  # Budget not exceeded

# Define a function to handle the trigger logic
def check_budget_trigger(sender_id, receiver_id, amount):
    # Check if receiver_id is in the predefined list
    if receiver_id in receiver_categories:
        rec_category = receiver_categories[receiver_id]
        # Check if the sender has set a budget for this category and if the transaction amount exceeds it
        if check_budget(sender_id, rec_category, amount):
            # Handle budget exceeded scenario (you can log or take any other action here)
            # For simplicity, I'm just printing a message
            print("Budget Exceeded!")
            return False  # Budget exceeded, don't insert into transactions table
    return True  # Budget not exceeded, proceed with insertion


    #Checks whether the transaction amount is greater and exceed the budget amount with particular category
    #It also checks whether receiver belongs to an organiztion

In [ ]:
def update_budget(sender_id,reciver_id,amount):
    category_id = receiver_categories[reciver_id]
    x =con.execute(f"select budget_amount from Budget where username  = '{sender_id}' and  category_id = '{category_id}'").fetchone()[0]
    x-=amount
    con.execute(f"update Budget set budget_amount = {x} where username = '{sender_id}' and category_id = '{category_id}'")
    y  =con.execute(f"select total_amount from Budget where username ='{sender_id}' and category_id = '{category_id}'").fetchone()[0]
    y+=amount
    con.execute(f"update Budget set total_amount = {y} where username ='{sender_id}' and category_id = '{category_id}'")

    con.commit()
    print("Transaction inserted successfully!")

    #When the transaction is done within the budget amount the budget table is updated.
    #The budget amount is deducted and added to the total spent amount

In [ ]:
def authenticate_user(username, pin):
    user = con.execute("SELECT username FROM Users WHERE username=? AND (pin=? OR pin IS NULL)", (username,pin)).fetchone()
    if user:
        return user[0]
    else:
        return None

#Checking whether the user with the entered username exists.
#if exists, authentication is complete. If not it is an invalid/non-existing user.

In [ ]:
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

# Email configuration
EMAIL_ADDRESS = 'atheendreramesh@gmail.com'
EMAIL_PASSWORD = 'ddjq gtlz kgtk ggtk'
SMTP_SERVER = 'smtp.gmail.com'
SMTP_PORT = 587

#SMTP-Simple Mail Transfer Protocol

def send_email(sender_email, receiver_email, subject, body):
    msg = MIMEMultipart('alternative')
    msg['From'] = sender_email
    msg['To'] = receiver_email
    msg['Subject'] = subject

    msg.attach(MIMEText(body, 'html'))

    with smtplib.SMTP(SMTP_SERVER, SMTP_PORT) as s:
        s.starttls()
        s.login(EMAIL_ADDRESS, EMAIL_PASSWORD)
        s.send_message(msg)
#This block of code establishes a connection to the SMTP server specified by SMTP_SERVER and SMTP_PORT.
#It then starts TLS encryption (starttls()), logs in to the SMTP server using the sender's email address and password (login()), and sends the email message (send_message(msg)).

In [ ]:
def transact2(senders_id, receivers_id, amount):
    if receivers_id is None:
        receivers_id = input("Please enter the receiver's username: ")
        amount = int(input("Please enter the amount: "))

    if senders_id != receivers_id:
        receiver_exists = con.execute("SELECT 1 FROM Users WHERE username=?", (receivers_id,)).fetchone()

        # makes sure you're not sending it to the same user
        if not receiver_exists:
            print("Receiver ID not found")
            return
        else:
            # Check if the sender has enough balance
            sender_balance = con.execute("SELECT bankbalance FROM balance WHERE username=?", (senders_id,)).fetchone()[0]
            if sender_balance < amount:
                print(f"Insufficient balance. Your current balance is {sender_balance}.")
                return

            category_id = None
            if receivers_id in receiver_categories:
              category_id = receiver_categories[receivers_id]

              if check_budget_trigger(senders_id, receivers_id, amount):
                  update_budget(senders_id, receivers_id, amount)
                  category_id = receiver_categories[receivers_id]

                  try:
                   con.execute("BEGIN")
                   con.execute("INSERT INTO transactions (senders_id, receivers_id, amount, category_id) VALUES (?, ?, ?, ?)",
                            (senders_id, receivers_id, amount, category_id))
                   con.commit()
                   print("Transaction successful.")

                # Send emails after successful transaction
                   sender_email = con.execute("SELECT email FROM Users WHERE username=?", (senders_id,)).fetchone()[0]
                   receiver_email = con.execute("SELECT email FROM Users WHERE username=?", (receivers_id,)).fetchone()[0]

                   sender_subject = "Transaction Successful"
                   sender_body = f"Your transaction of {amount} to {receivers_id} is successful."
                   send_email(EMAIL_ADDRESS, sender_email, sender_subject, sender_body)

                   receiver_subject = "You received a transaction"
                   receiver_body = f"You received {amount} from {senders_id}."
                   send_email(EMAIL_ADDRESS, receiver_email, receiver_subject, receiver_body)

                  except Exception as e:
                    con.rollback()
                    print(f"Error: {e}")
                    # Send email for transaction failure
                    sender_email = con.execute("SELECT email FROM Users WHERE username=?", (senders_id,)).fetchone()[0]
                    sender_subject = "Transaction Failed"
                    sender_body = "Your transaction failed. Please try again later."
                    send_email(EMAIL_ADDRESS, sender_email, sender_subject, sender_body)

            else:
               try:
                   con.execute("BEGIN")
                   con.execute("INSERT INTO transactions (senders_id, receivers_id, amount, category_id) VALUES (?, ?, ?, ?)",
                            (senders_id, receivers_id, amount, category_id))
                   con.commit()
                   print("Transaction successful.")

                # Send emails after successful transaction
                   sender_email = con.execute("SELECT email FROM Users WHERE username=?", (senders_id,)).fetchone()[0]
                   receiver_email = con.execute("SELECT email FROM Users WHERE username=?", (receivers_id,)).fetchone()[0]

                   sender_subject = "Transaction Successful"
                   sender_body = f"Your transaction of {amount} to {receivers_id} is successful."
                   send_email(EMAIL_ADDRESS, sender_email, sender_subject, sender_body)

                   receiver_subject = "You received a transaction"
                   receiver_body = f"You received {amount} from {senders_id}."
                   send_email(EMAIL_ADDRESS, receiver_email, receiver_subject, receiver_body)

               except Exception as e:
                    con.rollback()
                    print(f"Error: {e}")
                    # Send email for transaction failure
                    sender_email = con.execute("SELECT email FROM Users WHERE username=?", (senders_id,)).fetchone()[0]
                    sender_subject = "Transaction Failed"
                    sender_body = "Your transaction failed. Please try again later."
                    send_email(EMAIL_ADDRESS, sender_email, sender_subject, sender_body)


    else:
        print("Cannot transact to the same sender and receiver.")

In [ ]:
import getpass
def login():
  username=input("pls enter username: ")
  pin=getpass.getpass("pls input pin: ")
  pin=encrypt(int(pin))
  x=authenticate_user(username,pin)
  if x:
    print("log in successful.")
    return username
  else:
    print("invalid username or pin.")

senders_id=login()

pls enter username: Ramyashree_04

In [ ]:
def transaction(senders_id):
    pin = getpass.getpass("Please enter pin: ")
    pin = encrypt(int(pin))
    user_id = authenticate_user(senders_id,pin)
    if user_id:
        transact2(senders_id,None,None)
    else:
        print("Authentication failed. Incorrect username or PIN.")
transaction(senders_id)

Please enter pin: ··········
Please enter the receiver's username: Ramyashree_04
Please enter the amount: 120
Transaction successful.

In [ ]:
# con.execute("select * from transactions").fetchall()

1. checked all test cases budget execeeding,same user and reciver,reciver not found and a succesful transaction
2. transcation to a non-organisation will have the category as None this could be changed if needed

In [ ]:
# con.execute("select * from Budget where username=  'Atheendre_ram'").fetchall()

In [ ]:
def getbankbalance(senders_id):
    pin = getpass.getpass("Please enter pin: ")
    pin = encrypt(int(pin))
    # Authenticate user
    user_id = authenticate_user(senders_id,pin)
    if user_id:
        result = con.execute("SELECT bankbalance FROM balance WHERE username = ?", (senders_id,)).fetchone()
        if result:
            return result[0]
        else:
            return "User balance not found"
    else:
        return "Authentication failed. Incorrect username or PIN."
print("Your bank balance is:", getbankbalance(senders_id))

Please enter pin: ··········
Your bank balance is: 91091

In [ ]:
def transaction_history():
    pin = getpass.getpass("Please enter pin: ")
    pin = encrypt(int(pin))

    user_id = authenticate_user(senders_id,pin)
    if user_id:
        result = con.execute("SELECT senders_id, receivers_id, amount, date, time,category_id FROM transactions WHERE senders_id = ? OR receivers_id = ?", (senders_id,senders_id )).fetchall()
        if result:
            for transaction in result:
                print(f"Sender: {transaction[0]}, Receiver: {transaction[1]}, Amount: {transaction[2]}, Date: {transaction[3]}, Time: {transaction[4]}, category: {transaction[5]}")
        else:
            print(f"No transactions found for user {senders_id}")
    else:
        print("Authentication failed. Incorrect username or PIN.")

transaction_history()

Please enter pin: ··········
Sender: Atheendre_ram, Receiver: ApolloHealth_12345, Amount: 10, Date: 2024-05-04, Time: 18:45:13, category: MED
Sender: Atheendre_ram, Receiver: ApolloHealth_12345, Amount: 10, Date: 2024-05-04, Time: 18:45:47, category: MED
Sender: Atheendre_ram, Receiver: ApolloHealth_12345, Amount: 10, Date: 2024-05-04, Time: 18:46:28, category: MED
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 1, Date: 2024-05-04, Time: 18:54:42, category: None
Sender: Skanda_Pv, Receiver: Atheendre_ram, Amount: 10, Date: 2024-05-04, Time: 19:01:36, category: None
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-04, Time: 21:04:33, category: None
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-05, Time: 14:23:43, category: None
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-05, Time: 14:24:33, category: None
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-05, Time: 14:25:07, category: None
Sender: Atheendre_ram, Receiver: ApolloHealth_12345, Amount: 444, Date: 2024-05-05, Time: 16:03:36, category: MED
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-05, Time: 16:51:52, category: Misc
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 300, Date: 2024-05-05, Time: 16:53:43, category: Misc
Sender: Atheendre_ram, Receiver: Bigb_2342, Amount: 10, Date: 2024-05-05, Time: 20:50:01, category: GRC
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 10, Date: 2024-05-05, Time: 20:50:28, category: Misc
Sender: Atheendre_ram, Receiver: Bigb_2342, Amount: 20, Date: 2024-05-05, Time: 20:51:39, category: GRC
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 12, Date: 2024-05-05, Time: 20:52:31, category: None
Sender: Atheendre_ram, Receiver: FoodieBangalore99, Amount: 500, Date: 2024-05-05, Time: 21:02:42, category: F&B
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 123, Date: 2024-05-06, Time: 07:18:51, category: None
Sender: Atheendre_ram, Receiver: Ramyashree_04, Amount: 120, Date: 2024-05-20, Time: 16:08:42, category: None

In [ ]:
def autopay(senders_id):
    import time
    pin = getpass.getpass("Please enter pin: ")
    pin = encrypt(int(pin))
    user_id=authenticate_user(senders_id,pin)
    receivers_id=input("pls enter receivers_id: ")
    amount=int(input("pls enter amount: "))
    if user_id:
        transact2(senders_id,receivers_id,amount)
        while True:
            print("autopay every 30 days.")
            time.sleep(30)#30 seconds just to show
            transact2(senders_id, receivers_id, amount)
            choice = input("Do you want to end the transaction? (yes/no): ")
            if choice.lower() == "yes":
                break
    else:
        print("Authentication failed. Incorrect username or PIN.")
autopay(senders_id)

Please enter pin: ··········
pls enter receivers_id: Ramyashree_04
pls enter amount: 10
Transaction successful.
autopay every 30 days.
Transaction successful.
Do you want to end the transaction? (yes/no): no
autopay every 30 days.
Transaction successful.
Do you want to end the transaction? (yes/no): yes

In [ ]:
def alltransactions():
  return con.execute("select * from transactions").fetchall()
alltransactions()

[(1,
  'Atheendre_ram',
  'ApolloHealth_12345',
  10,
  '2024-05-04',
  '18:45:13',
  'MED'),
 (2,
  'Atheendre_ram',
  'ApolloHealth_12345',
  10,
  '2024-05-04',
  '18:45:47',
  'MED'),
 (3,
  'Atheendre_ram',
  'ApolloHealth_12345',
  10,
  '2024-05-04',
  '18:46:28',
  'MED'),
 (4,
  'Ramyashree_04',
  'ApolloHealth_12345',
  10,
  '2024-05-04',
  '18:47:10',
  'MED'),
 (5,
  'Ramyashree_04',
  'ApolloHealth_12345',
  10,
  '2024-05-04',
  '18:47:42',
  'MED'),
 (6, 'Atheendre_ram', 'Ramyashree_04', 1, '2024-05-04', '18:54:42', None),
 (7, 'Skanda_Pv', 'Atheendre_ram', 10, '2024-05-04', '19:01:36', None),
 (8, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-04', '21:04:33', None),
 (9, 'Aasish_02', 'Ramyashree_04', 100000, '2024-05-04', '00:07:50', None),
 (10, 'Ramyashree_04', 'Bigb_2342', 10, '2024-05-04', '00:38:42', 'GRC'),
 (11, 'Ramyashree_04', 'Netflix_Buff', 200, '2024-05-04', '00:44:11', 'CE'),
 (12, 'Ramyashree_04', 'Netflix_Buff', 200, '2024-05-04', '00:44:44', 'CE'),
 (13, 'Ramyashree_04', 'Netflix_Buff', 200, '2024-05-04', '00:50:14', 'CE'),
 (14, 'Ramyashree_04', 'Netflix_Buff', 200, '2024-05-04', '01:29:07', 'CE'),
 (15, 'Ramyashree_04', 'Netflix_Buff', 200, '2024-05-04', '01:46:54', 'CE'),
 (16, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-05', '14:23:43', None),
 (17, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-05', '14:24:33', None),
 (18, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-05', '14:25:07', None),
 (19,
  'Atheendre_ram',
  'ApolloHealth_12345',
  444,
  '2024-05-05',
  '16:03:36',
  'MED'),
 (20, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-05', '16:51:52', 'Misc'),
 (21, 'Atheendre_ram', 'Ramyashree_04', 300, '2024-05-05', '16:53:43', 'Misc'),
 (22, 'Atheendre_ram', 'Bigb_2342', 10, '2024-05-05', '20:50:01', 'GRC'),
 (23, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-05', '20:50:28', 'Misc'),
 (24, 'Atheendre_ram', 'Bigb_2342', 20, '2024-05-05', '20:51:39', 'GRC'),
 (25, 'Atheendre_ram', 'Ramyashree_04', 12, '2024-05-05', '20:52:31', None),
 (26,
  'Atheendre_ram',
  'FoodieBangalore99',
  500,
  '2024-05-05',
  '21:02:42',
  'F&B'),
 (27, 'Atheendre_ram', 'Ramyashree_04', 123, '2024-05-06', '07:18:51', None),
 (28, 'Atheendre_ram', 'Ramyashree_04', 120, '2024-05-20', '16:08:42', None),
 (29, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-20', '16:10:20', None),
 (30, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-20', '16:10:52', None),
 (31, 'Atheendre_ram', 'Ramyashree_04', 10, '2024-05-20', '16:11:27', None)]

In [ ]:

pd.read_sql("SELECT * FROM sqlite_master where type='table'",con)

,type,name,tbl_name,rootpage,sql
0,table,sqlite_sequence,sqlite_sequence,9,"CREATE TABLE sqlite_sequence(name,seq)"
1,table,Users,Users,2,CREATE TABLE Users (\n username...
2,table,Category,Category,5,CREATE TABLE Category (\n category_id text ...
3,table,balance,balance,7,CREATE TABLE balance (\n bankbalance_id INT...
4,table,transactions,transactions,11,CREATE TABLE transactions (\n transaction_i...
5,table,people,people,17,CREATE TABLE people (\n id INTEGER ...
6,table,Budget,Budget,4,CREATE TABLE Budget (\n budget_id INTEGER P...

In [ ]:
from openpyxl import Workbook, load_workbook  #For excel files
import sqlite3
from datetime import datetime, timedelta  #For date and time

# Function to fetch all updates from SQLite database for each table
def fetch_updates_from_database():
    connection = sqlite3.connect('Team3/dbmsproj.sqlite')
    cursor = connection.cursor()

    updates = {}

    cursor.execute("SELECT * FROM users")
    updates['users'] = cursor.fetchall()

    cursor.execute("SELECT * FROM category")
    updates['category'] = cursor.fetchall()

    cursor.execute("SELECT * FROM budget")
    updates['budget'] = cursor.fetchall()

    cursor.execute("SELECT * FROM balance")
    updates['balance'] = cursor.fetchall()

    cursor.execute("SELECT * FROM transactions")
    updates['transactions'] = cursor.fetchall()

    return updates

# Function to update existing records in Excel file with new data
def update_excel_file(updates):
    wb = Workbook()

    # Update data for each sheet
    for sheet_name, data in updates.items():
        ws = wb.create_sheet(title=sheet_name)

        # Specify custom column names for each sheet
        custom_column_names = {
            'users': ['Username', 'Name', 'Email', 'Encrypted Pin'],
            'category': ['Category ID', 'Category Name'],
            'budget': ['Budget ID', 'Usename', 'Category ID', 'Budget amount','Total Spent', 'Start Date', 'End Date'],
            'balance': ['Balance ID', 'User ID', 'Amount'],
            'transactions': ['Transaction ID', 'Sender Username', 'Receiver Username', 'Amount', 'Date', 'Time', 'Category_ID']
        }

        # Add custom column names to the sheet
        column_names = custom_column_names.get(sheet_name, [])
        for col, name in enumerate(column_names, start=1):
            ws.cell(row=1, column=col, value=name)

        # Add data to the sheet
        for row_idx, row_data in enumerate(data, start=2):
            for col_idx, value in enumerate(row_data, start=1):
                ws.cell(row=row_idx, column=col_idx, value=value)
    wb.remove(wb['Sheet'])  # Remove default sheet
    wb.save('Team3/Records.xlsx')

# Main function to fetch updates and update Excel file
def main():
    updates = fetch_updates_from_database()
    if updates:
        update_excel_file(updates)
        utc_now = datetime.utcnow()  # Get current UTC time
        ist_now = utc_now + timedelta(hours=5, minutes=30)  # Add 5 hours and 30 minutes for IST
        print(f"Excel file updated with new updates at {ist_now.strftime('%Y-%m-%d %H:%M:%S')} IST")
    else:
        print("No updates found.")

if __name__ == "__main__":
    main()

Excel file updated with new updates at 2024-05-20 16:11:52 IST

In [ ]:
con.close()